travis:
  secure:
    BINSTAR_TOKEN: Z+YNCLaxf4EhyT5yi7TVsqlobAHZDX+5qcX2UC6ceNPXg5qqGD/Mtiy40t7DhL3rjxwyLSg6ibuurMkfiW7YCjV7LhpEe9+ypmJguOYqEPLmRcU+f9qLf+jC6rYVYOHakzjhSSUbzNk/dE2fyzyp0ZTgxhN7FIfnPfs6vYzsB6n1n9OItdpRS+syOHZTDVMcJ0VM8TrnlM6pAatcoLHaUGvadka1rJMxgI2AoYya2/qjp5EY0WRd0uDxxrY2HW/shoFTxnYEiRBnzDnEKeWfyjfiuI9hUSoG7h4ocSVo03pu9U4sxs2cOfQlKaZkyGGGyMgWjLtYCexOLntMhngqd7rzF2qEVjG+/SMUcyl/C9LlvRjyTBOm+FxW9VNAqBNM1JnXUXHM6VCzUmonRbHLMsl2sd5yeUnqQK2QSgYFHdOSN0Zlrwkdzi8DPL5BEPolplOiy+xZdlcUkMHegVZ8UhDEiknN9XPjTyS6/p3S2GhZddUFHJ7yRl6Z4y29W27cRZELwqqoOX8q+tPfwlbg1Afi2mBXx5ooXbIVTzEU+MuxCJvzZzJYR65il1xcSoLIK+kcUxMI7++P+I7q8LGTT/vgitvKWlnTbwAz8aw+LjBHHHFOej3BnbEu4wLjf4Q8StI4ALhb36MnNmk/MIYMNzYbFbmxZolQvY4SJNnC3Aw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
